### ISSUE TITLE
Yarn and node version

### ISSUE THREAD

**Issue by RomainOliva** [RimacTechnology/semantic-release-s3#14]
### Issues

- [X] I have checked [existing issues](https://github.com/RimacTechnology/semantic-release-s3/issues) and there are no existing ones with the same request.

### Feature description

Hello,

Why do you need Node in version 18 minimal and yarn in version 3, the lib can work with yarn 1 and node 14 no ?

Can you lower the engine requirement in your package.json please ?

Thanks in advance,
Best regards.

**Comment by vuki656** [comment]
I lowered the node version to 14 and yarn to 1.

Haven't tested as we are on node 18 and yarn 3. 

If you encounter any problems let me know.

**Comment by RomainOliva** [comment]
Thank you very much for your reactivity ! I will try it :)
