### ISSUE TITLE
Error with regex 

### ISSUE THREAD

**Issue by RomainOliva** [RimacTechnology/semantic-release-s3#17]
### Issues

- [X] I have checked [existing issues](https://github.com/RimacTechnology/semantic-release-s3/issues) and there are no issues with the same problem.

### `semantic-release-s3` Version You Are Using

v2.2.2

### Your Config

Node: 16 (I tried in 18 it's the same problem)
Yarn: 1.22.17

### Steps to reproduce

Send a config like this : 

```
{
        awsAccessKeyName: 'LIBRARY_S3_ACCESS_KEY_ENV',
        awsSecretAccessKeyName: 'LIBRARY_S3_SECRET_ACCESS_KEY_ENV',
        removeDirectoryRoot: true,
        s3Bucket: {
          branchName: `my-bucket/v1.1.0`,
        },
        directoryPath: 'dist/**/*',
},
```

### Expected behavior

The problem came from this change :

https://github.com/RimacTechnology/semantic-release-s3/commit/e31cc03beccb52330ad313ba9ac1cc4c78d88407#diff-a7a74f2666de0f501942c3e3c0ff9146e86f8fb359f8cf521dcdb205490b0e3eR34

This throw the error below (i try in the chrome console too)

Do you have any idea of the problem ?

Thanks a lot :) 

### Actual behavior

```[3:40:14 PM] [semantic-release] › ✖  An error occurred while running semantic-release: SyntaxError: Invalid regular expression: /\$([_a-z]+\w*)|\${(\w*)}/: Incomplete quantifier
    at publish (/home/runner/work/gtr-form-renderer/gtr-form-renderer/node_modules/@rimac-technology/semantic-release-s3/lib/publish.js:46:55)
    at async validator (/home/runner/work/gtr-form-renderer/gtr-form-renderer/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/gtr-form-renderer/gtr-form-renderer/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/home/runner/work/gtr-form-renderer/gtr-form-renderer/node_modules/p-reduce/index.js:16:18) {
  pluginName: '@rimac-technology/semantic-release-s3'
}
The automated release failed with SyntaxError: Invalid regular expression: /\$([_a-z]+\w*)|\${(\w*)}/: Incomplete quantifier
    at publish (/home/runner/work/gtr-form-renderer/gtr-form-renderer/node_modules/@rimac-technology/semantic-release-s3/lib/publish.js:46:55)
    at async validator (/home/runner/work/gtr-form-renderer/gtr-form-renderer/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/gtr-form-renderer/gtr-form-renderer/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/home/runner/work/gtr-form-renderer/gtr-form-renderer/node_modules/p-reduce/index.js:16:18) {
  pluginName: '@rimac-technology/semantic-release-s3'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by RomainOliva** [comment]
My bad it's not the JS compilation, it's from a commit change, I edit the issue

**Comment by mario-jerkovic** [comment]
Thank you for reporting the issue, we will take a look ang get back to you.

**Comment by RomainOliva** [comment]
I have the fix but I don't have the right to push my PR, there is the fix :

```
const bucketPrefix = bucketPrefixes.join(path.sep).replace(/\$([_a-z]+\w*)|\$\{(\w*)\}/giu, (match, p1, p2) => {
        return process.env[p1 || p2] ?? match
    })
```

**Comment by vuki656** [comment]
> I have the fix but I don't have the right to push my PR, there is the fix :
> 
> ```
> const bucketPrefix = bucketPrefixes.join(path.sep).replace(/\$([_a-z]+\w*)|\$\{(\w*)\}/giu, (match, p1, p2) => {
>         return process.env[p1 || p2] ?? match
>     })
> ```
> 
> You have just to escape `{` and `}` caracters

Not sure I follow, are you not able to open a PR or? 

If this is tested, we can update it.

**Comment by RomainOliva** [comment]
Yes i don't have permission : <img width="1076" alt="image" src="https://user-images.githubusercontent.com/16322590/222419253-b0359296-9629-472d-90e3-28b13cf810e5.png">

I test the regex online yes : 

![image](https://user-images.githubusercontent.com/16322590/222419559-df189c11-60d5-439d-83c3-20b735ce3b60.png)

it's the same regex but escaped to avoid the js error

**Comment by RomainOliva** [comment]
Can you just commit the fix and release with the regex escaped please 😇 ?

**Comment by mario-jerkovic** [comment]
@RomainOliva Yes, you don't have permission to push in this repository. If you want to contribute than follow this guide on how to open a PR from fork a repository [LINK](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by RomainOliva** [comment]
Okay I see :) As there was no contribution part in the readme I didn't know which method you had chosen.
I would do like that for my suggestion in the other issue.

Can you do the commit for this time? To fix the library, because if you update it in your projects you will also get this error

**Comment by RomainOliva** [comment]
The PR is created : https://github.com/RimacTechnology/semantic-release-s3/pull/18
